# Site settings
title: Tran Dinh Hoang
description: チャン ディン ホアン
#logo: assets/img/logo.png
#show_downloads: true
github:
  is_project_page: false
theme: jekyll-theme-hacker # you can change the theme here, choose one from https://pages.github.com/themes/
markdown: GFM
